### ISSUE TITLE
[HELP/QUESTION] How to add sounds to the pets

### ISSUE THREAD

**Issue by RedSparr0w** [Adrianotiger/desktopPet#17]
Was just wondering how you add sounds to the pets.

Noticed the "Allow sounds" option:
![image](https://user-images.githubusercontent.com/7288322/29258849-657423dc-8111-11e7-8647-aeff8b2d5bd1.png)

But i cannot find anything on the editor page or in the [documentation for the editor](http://esheep.petrucci.ch/Help/Manual%20-%20online%20editor.pdf)

**Comment by Adrianotiger** [comment]
Hi RedSparrow. It is nice to see, that you are still active and are still using this program :D
It is hidden because it isn't working good and because I need to put some limits on the sounds to upload (I don't want that everyone can upload up to 1GB of mp3s :P).
If you go to the generator page, write sound.php instead of generator.mp3 and you will be able to upload sounds to your pet :) Only MP3 are allowed.

**Comment by LordPsylex** [comment]
can you share the one with sounds? i miss hearing this thing sneeze and get beamed away lol :D

**Comment by Adrianotiger** [comment]
> can you share the one with sounds? i miss hearing this thing sneeze and get beamed away lol :D

Under options you will find the green sheep. This one has sounds.
