### ISSUE TITLE
Program doesn't work in cultures that use comma as decimal separator

### ISSUE THREAD

**Issue by Maykeye** [Adrianotiger/desktopPet#2]
Ver 0.9.0.

On start the program throws this exception

     System.FormatException: Входная строка имела неверный формат.
        в System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
        в System.Double.Parse(String s)
        в DesktopPet.Xml.loadAnimations(Animations animations)
        в DesktopPet.StartUp.timer1_Tick(Object sender, EventArgs e)
        в System.Windows.Forms.Timer.OnTick(EventArgs e)
        в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
        в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

It happens because Double.Parse(String) by default uses current culture settings (unless ts explicitly told to use [CultureInfo.InvariantCulture](http://stackoverflow.com/questions/9760237/what-does-cultureinfo-invariantculture-mean)), which means that e.g. "0.8"(from `<opacity>0.8</opacity>`) is not a valid double in e.g. Russian system.

**Comment by Adrianotiger** [comment]
Thank you Maykeye for opening the first issue on this project!!!! And also for giving me so much info about the error. I will solve this bug as soon as possible.

**Comment by Adrianotiger** [comment]
Fixed!
Maybe in future I should allow "." and "," because now you can't use the "," in your XML (and so you have to use another culture than yours to write a personal XML). But for now it should work like expected in all ","-culture countries :D 
Thank you again! :+1:

**Comment by Adrianotiger** [comment]
Now I use XML serialisation. So this culture problem should not be there anymore.
Thank you again for your feedback!

**Comment by swunder** [comment]
Hi Andruanotiger, over google I found this comments. I am facing the same issue as your software did on my software. May I ask how did you solve this problem?

BR STefan

**Comment by Adrianotiger** [comment]
Hi Swunder,
there are 2 ways to solve. One is the culture and the other is the serialisation.
On the first, you get your culture to parse everything (so it works in countries with other cultures):
Instead of writing:
sText = sText.Replace("screenW", Screen.PrimaryScreen.Bounds.Width.ToString());
You write:
sText = sText.Replace("screenW", Screen.PrimaryScreen.Bounds.Width.ToString(CultureInfo.InvariantCulture));

The better way is the serialisation, where you create a struct with the same tree like the xml and C# will convert automatically the values in the xml to fit the datatype in the C# structure. 
See https://support.microsoft.com/en-us/kb/815813
or just give a look to my Xml.cs code to see how simple it is :D
