### ISSUE TITLE
A crash sliding down window edge.

### ISSUE THREAD

**Issue by rluiten** [Adrianotiger/desktopPet#3]
Windows 10 64 bit.
When it slid down a window edge and when it encountered another window border below it it stopped as you would expect but when it stopped it crashed.

I've been considering writing a replacement for esheep a long time - well done!

Also a side note, I've had it active and bring a window to the foreground when it collides with it, I think this is a very bad idea, it should be totally passive with no side effects to windows in my opinion.

**Comment by Adrianotiger** [comment]
Hi Robin,
thank you for your issue (the first one!!!!) 😺 
I am able to reproduce it and found the error - out of index error because it was the last animation. I will try to release an update this week end.
The project is nice but need a lot of work to give a more powerful editor, maybe an offline editor instead of the webpage. I want also insert the possibility to detect other sheeps on the desktop for interaction but I dont have much time anymore.

The sheep bring the window in foreground, this is right. That's because the original sheep did it 👅  But I can understand what you mean and it isn't a "nice" effect. I will remove it in the next release and add an option in the settings to activate this functionality.

**Comment by rluiten** [comment]
Cool, I just forked the project to see if I might be able to track it down, but starting from zero so will have to develop some familiarity with it.

**Comment by Adrianotiger** [comment]
If you want solve it immediately for you, you can go to line 628 on Animations.cs and replace the line with:
if(!SheepAnimations.ContainsKey(id))
It is a dictionary of id and I wrote SheepAnimations[id] instead. By the way, if you press SHIFT when you launch the application, you will be able to see a debug window and interact with the sheep if you right-press on it.

**Comment by Adrianotiger** [comment]
Update available. Solved the bug and window will not be set in foreground anymore (it wasn't handled correctly before).

**Comment by rluiten** [comment]
Did you intend to not add a binary to your release for this ?
Not that it matters I can build but many others will not be able to.
