### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by meadows19** [Adrianotiger/desktopPet#32]
Hello.

I want to run this application as a portable application.

So I don't install it, and run it directly from the .exe

However, it leaves the config file here:

C:\Users\name\AppData\Local\Adriano

Instead of this, is it possible to leave the config file in the same directory as the exe, in the non-installed version?

Thank you.

**Comment by Adrianotiger** [comment]
Hi Meadows,
the application was made to work as portable application. But the settings are saved in %appdata% because there is a possibility that the exe folder is protected.
I will try to update the application in this way:
- if you don't install the application, settings are saved inside the exe folder
- if you install the application, settings are saved inside appdata folder

But I can't compile it with a certificate, since it expired. I will add the exe inside github or you can compile it by yourself if you want, ok? Give me some days to find a solution and to create the "portable" project, since the current project works only on Windows 10.

**Comment by Adrianotiger** [comment]
I made a release. You should be able to download it from the home page or you can download it from here:
https://github.com/Adrianotiger/desktopPet/releases/tag/Portable

Let me know if it is ok for you :)

**Comment by meadows19** [comment]
Works great! Thank you so much!
