### ISSUE TITLE
Missing Animations for sheep/gsheep?

### ISSUE THREAD

**Issue by versavius** [Adrianotiger/desktopPet#35]
Apologies but i have half inched a comment from the youtube comments for esheep :) Just wondered if all the animations that were in the original esheep and gsheep are in the UWP version ?

If not could we get them added if its possible, that would be awesome !

> This is just a shadow of the original one. It doesn't pee on the flowers that very rarely pop up like it used to do occasionally?
> 
> Now it eats them more often than not at the edge of the screen almost out of shot.
> Where is the black sheep that would suddenly make an appearance all by itself,, or the flying saucer that beamed eSheep up?
> 
> This one walks, sleeps, yawns, jumps and runs but that is all it does, I was hoping for the original sheep.exe in all its glory - this one is a waste of time. Been running it for half an hour and I've seen half of the flowers being eaten - once.....No Black sheep, no flying saucer, pity!
 
Thanks

David

**Comment by Adrianotiger** [comment]
Hi David!
I developed the application to allow anyone to create a mate. I know, the one coming with the app doesn't have so much animations. The green one (was not made by me) has a lot of animations!
Just open the options and download the green one.
UWP and Desktop application use the same screen mate directory now, you can find the directory with all screen mates on GitHub:
https://adrianotiger.github.io/desktopPet/Pets/

I wrote to the developer to ask them to port their mate on github instead of my webpage. But only 2 ported their mate to GitHub.

But, you are welcome if you want create your pet :D
