### ISSUE TITLE
Systray right-click menu closes itself

### ISSUE THREAD

**Issue by KAMiKAZOW** [Adrianotiger/desktopPet#40]
Latest Win10 here. The context menu closes by itself directly after I right-click on the icon.

It seems to be worse if the number of sheep is higher.

**Comment by Adrianotiger** [comment]
I know. If your pet is walking on the taskbar, the taskbar will hide your pet.
The only way to bring it to top again is to set the top most again. But in this way, the context menu will loose the focus.

I need to find a woraround for this. Maybe creating a window, instead of a context menu.

Don't know what is the best solution to be honest...

**Comment by Adrianotiger** [comment]
Should be solved with the version 1.2.6 (will not steal the focus anymore until you set it in the options).
