### ISSUE TITLE
Noticed tool tips in web pages don't appear in Chrome at least with pet running.

### ISSUE THREAD

**Issue by rluiten** [Adrianotiger/desktopPet#5]
Not sure it matters, but might be worth exploring to see if the side effect might be avoided.
If it can't be avoided maybe mention it in the documentation so it doesn't frustrate or confuse people.

**Comment by Adrianotiger** [comment]
I can see the tooltips of Windows, Internet Explorer and also from Edge. So it seem more one of the Chrome bugs. Maybe Chrome doesn't like if another window is set as "TopMost". But if you can't see any tooltip in Chrome only because another program is in foreground, Google should solve the bug, not me ;)

**Comment by rluiten** [comment]
Just thought I'd mention so you are aware and possibly others might be aware of a side effect.
As I said "Not sure it matters" :).
