### ISSUE TITLE
Too many pets makes right clicking on the icon at the taskbar not possible

### ISSUE THREAD

**Issue by Adriansun** [Adrianotiger/desktopPet#59]
Hi,

Sometimes, when right clicking on the eSheep program icon and the alternatives / options menu appear, then the menu will disappear by it self after maybe 0.2 seconds. This makes it hard to, for example, being able to shut down the program. This is even more true when there are a lot of pets on the screen. It is a bug.

**Comment by Adrianotiger** [comment]
Hi Adriansun,
Yes it is definitively a bug.
The problem is that windows and taskbar continue to steal the "onTop" attribute to the sheep. So if the sheep falls behind the taskbar, you can't see it again.
With the sheep it isn't a problem. With the Negima mates (girls with legs over the taskbar), the legs are cutted every time. So I begun to check if the pet is over the taskbar and re-take the focus.

- Now, if you press on the tray icon, the focus is lost and the pet will take back the focus to stay on top of the taskbar.
- Unfortunately this will close also the menu.
- It happens with all menus opened as tray icon (not only from the app) and this is really annoying

I have to find another solution. But still doesn't know what could be the best solution. 
A workaround is to leave the taskbar on top and take the focus only every 30 seconds for example - managed by the main application and not from every single pet.

**Comment by Estecka** [comment]
From what I've observed, DesktopPet's menu seems to be the only one to actually close. With other applications, the pet _do_ come on top if it was being masked by the menu, but the menu still persists behind the pet.

Until a proper solution is found, I'd like to see an option to disable this behaviour completely; proper access to the tray menus seems more important to me than having _some_ pets being masked by the taskbar.

**Comment by Adrianotiger** [comment]
solved with the 1.2.6 version.
You can activate the feature again under options. But will not steal the taskbar every 1-2 seconds as before.
